Add section for Management of the WIS1 Catalogue
wmo-im/wis2-transition-guide pull request #11
Opened 2023-11-20 11:50 UTC by kaiwirt

2023-12-05 11:33 UTC, kaiwirt commented
@tomkralidis Anything to add from your side?

2023-12-08 13:38 UTC, tomkralidis requested changes
Minor changes requested.  As well, in general:

- quality "metadata" with "discovery metadata"
- we should be consistent with SHOULD vs. should, MAY vs may, etc.  I would suggest "should", "may" here, as the guide is just that, a guide.

2023-12-08 13:38 UTC, tomkralidis commented on transition-guide/sections/wis1cat.adoc
> +With the start of the preoperational phase of WIS2, GISCs do no longer need to maintain and provide their own WIS1 Catalogue. In order to be able to decommission their copies of the Catalogue, GISCs
- preoperational -> pre-operational
- liasse -> liase
- qualify metadata (i.e. WIS1 discovery metadata)
- general question, but example here: we mention ET-W2AT, ET-OM.  Do we make these more generic (i..e WMO, INFCOM)?  Note this will also apply to some requirements in WTH (cc @golfvert @efucile)
- "...from GTS and WIS1 to WIS2 is advanced": can/should we be more concise here?

2023-12-08 13:38 UTC, tomkralidis commented on transition-guide/sections/wis1cat.adoc
> +With the start of the preoperational phase updates to WIS1 metadata SHOULD be limited to important changes. Important changes are limited to updates to the contact points or to changes, that affect d
- preoperational -> pre-operational
- I would enumerate the important changes as a bulleted list, so:

```
Important changes are limited to the following items in cases where they require updates to WIS1 discovery metadata:
- updates to the points of contact 
- updates to the data formats/encodings
- updates to the contents of the data
```

2023-12-08 13:38 UTC, tomkralidis commented on transition-guide/sections/wis1cat.adoc
> +New metadata should not be added to the WIS1 Catalogue any more. Instead new data should only be added in WCMPv2 to the Global Discovery Catalogue for WIS2.
WCMPv2 -> WCMP2

2023-12-08 14:47 UTC, kaiwirt commented on transition-guide/sections/wis1cat.adoc
> +With the start of the preoperational phase of WIS2, GISCs do no longer need to maintain and provide their own WIS1 Catalogue. In order to be able to decommission their copies of the Catalogue, GISCs
Regarding "advanced". What i wanted to say is that the WIS1 Catalogue will be available until we think that enough centers have migrated towards WIS2 and that this date needs to be decided and announced by ET-W2AT or WMO or whoever is the correct party for that decision when the time is right

2023-12-10 12:26 UTC, tomkralidis approved these changes
Merging, I'll open an issue about identifying ETs/TTs in the guide.

2023-12-10 12:26 UTC, merged